### ISSUE TITLE
Week 9- functions Completed 

### ISSUE THREAD

**Issue by bhurda** [madisoncollege-it-programs/python-scripting-bhurda#11]

**Comment by cethenmc** [comment]
4 of 8 for now.  You may still receive full credit if you resubmit soon, showing you satisfy the lab's requirements, and reply to this ticket saying the corrections are ready.  As always, please book me if you struggle with a concept.

![image](https://user-images.githubusercontent.com/112707666/200014395-7d20b5f6-a356-4ecd-baa5-6896a278f97d.png)

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208478409-9410d785-3d69-45ed-8eb6-a78b5acbbdc1.png)
