### ISSUE TITLE
Week 10- did what i could

### ISSUE THREAD

**Issue by bhurda** [madisoncollege-it-programs/python-scripting-bhurda#12]

**Comment by cethenmc** [comment]
Please book some time with me, Brett.  Under instructor contact in Blackboard.  If none of those times work, then please send an email.  I get errors when I run it, so I cannot really grade it.

![image](https://user-images.githubusercontent.com/112707666/201417355-097607ca-0691-48ea-af82-09f6060e89eb.png)

**Comment by cethenmc** [comment]
Hi Brett - Are you okay?  I hope all is well and you have just been busy.  I have not heard back from you with the week 10 feedback I provided, and I noticed the subsequent week 11 was not submitted yet.  We covered week 12, which is due on Sunday.  There are only two more weeks of content before you review for the final project, so it is a tough time to fall behind.  I hope you will catch up this weekend.  Please let me know if there is anything I can do to help.  ~Chris

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208478463-7df3ce1e-aad0-45d9-b3a6-7c2f97c6da2a.png)
