### ISSUE TITLE
Ready for grading - Week 2, Lab 2 - first-script.py

### ISSUE THREAD

**Issue by bhurda** [madisoncollege-it-programs/python-scripting-bhurda#2]
Combined steps 1 and 2 hopefully alright

**Comment by cethenmc** [comment]
Brett.  I noticed you did not follow the directions of adding comments in the top.  More importantly, I would like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
    1. modify the file in NetLab with the added line at the top.
    2. update the file to be executable.
    3. add the file to staging (git add .)
    4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
    5. push to the git hub repository (git push)
    6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by cethenmc** [comment]
I am fixing your title on this issue to be more descriptive

**Comment by cethenmc** [comment]
Ben - please fix this for any credit on this assigment.

**Comment by cethenmc** [comment]
Looks good.
