### ISSUE TITLE
Ready for grading - Week 3 - strings.py

### ISSUE THREAD

**Issue by bhurda** [madisoncollege-it-programs/python-scripting-bhurda#3]

**Comment by cethenmc** [comment]
Changing the title of this issue to be acceptable

**Comment by cethenmc** [comment]
Brett.  I am recording a 4 of 8 for now, but please reply to this Issue when you have pushed corrections to GitHub.  Do **not** close this issue when you have done it.  I will close the ticket when the grading of your rework is complete.

- Please follow directions carefully, even down to the naming of the file (you started it with an uppercase S in strings.py).
- You are making the variable varLoot a string and it should be a float as shown in the assignment instructions.  After changing you may need to recheck #9-11.
- #12 is missing a space between the closing and ending brackets.  (For #12 and #13, I highly recommend downloading the instructions in Word and counting the spaces)
- #13 should have an equal number of spaces as there are dollar signs inside the brackets on #12.
- #14 you have a word misspelled.

Hope these instructions pinpoint where to look to get 100%.  Please reply to this Issue when you are ready for me to recheck.

Thanks.

Chris

**Comment by cethenmc** [comment]
Locked in grade and closing ticket.
