### ISSUE TITLE
Week #5 Ready for grading 

### ISSUE THREAD

**Issue by bhurda** [madisoncollege-it-programs/python-scripting-bhurda#5]
DataInteractions.py is the is assignment, tesxt is my notes.

**Comment by cethenmc** [comment]
Brett - You must follow directions.  I create scripts that help me with grading.  As a result, when you don't name your script files as requested (this assignment asked for you to "create a script called files.py."  You also are not following the instructions to keep your name and a description of your script in the file:  "Add a comment in your script to include the author (you) and a short description of your script."

The actual script has comments in the code that show you are doing Question 3 first then Question 1 then Question 2.  The corresponding code does not seem to follow that.

At first glance, your code for Question 3 (which is under Question 1 in your script), is not following what the homework is hoping to see.  You are supposed to save the full file contents to a variable one line at a time.  I don't see you doing this.

Please don't hesitate to reach out if you have more questions, but you need to resubmit this.  Please also make weeks 2, 3, and 4 scripts executable at the command line level so they can be graded.

~Chris

**Comment by cethenmc** [comment]
Hi Brett - I don't see corrections for this yet.  However, I will record a 2 of 8 for now, because the first questions under your Question 3 header correspond accurately to Question 1.  Please correct everything else previously mentioned for full credit.  ~Chris

**Comment by cethenmc** [comment]
Locked in grade and closing ticket.
