### ISSUE TITLE
Week #6 ready for grading Boolean.py

### ISSUE THREAD

**Issue by bhurda** [madisoncollege-it-programs/python-scripting-bhurda#7]

**Comment by cethenmc** [comment]
Recording 7 of 8 for now.  

You missed one of the 19 problems around #9/10 ish aread.

You can get full credit by correcting your skipped problem and adding the Author's name and short description as comments under the shebang line.

Thanks.

Chris

**Comment by cethenmc** [comment]
Locking in grade and closing ticket.
