### ISSUE TITLE
Week #6 ready for grading Flowcontrol.py 

### ISSUE THREAD

**Issue by bhurda** [madisoncollege-it-programs/python-scripting-bhurda#8]

**Comment by cethenmc** [comment]
Recording a 4 of 8 for now.  However, this should be resubmitted.  Reply to this when it is in a better place for my grading.  ~Chris

The task was to create a third door and modify to your taste.  The following is how it starts out, and I do not see the third as a choice.

**_You enter a dark room with two doors. 
Do you go through door #1 or door #2?
->_** 

After choosing 1, I get the following choice.  Choosing 3 renders an error.

**_1. Take the cake.
2. Scream at the bear.
3. Back out of door.
-> 3
Well, doing nothing is probably better.
You run away.
Traceback (most recent call last):
  File "./flowcontrol.py", line 59, in <module>
    if Loot == "1":
NameError: name 'Loot' is not defined_**

**Comment by cethenmc** [comment]
Locking in grade and closing ticket.
